-- Add new VisiteType enum values
ALTER TYPE "VisiteType" ADD VALUE IF NOT EXISTS 'CM';
ALTER TYPE "VisiteType" ADD VALUE IF NOT EXISTS 'ETUDEP';
ALTER TYPE "VisiteType" ADD VALUE IF NOT EXISTS 'LD';
ALTER TYPE "VisiteType" ADD VALUE IF NOT EXISTS 'MD';
